import image from '../images/movie-img.jpg'
export const movies = [
  {
    id: 1,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 2,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 3,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 4,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 5,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 6,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 7,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 8,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 9,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 10,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 11,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 12,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 13,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 14,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 15,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 16,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 17,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 18,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 19,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 20,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 21,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 22,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 23,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 24,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 25,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 26,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
]

export const savedMovies = [
  {
    id: 1,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 2,
    nameRU: '33 слова о дизайне',
    url: image,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
  {
    id: 3,
    nameRU: '33 слова о дизайне',
    url: image,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=wc0kH3KcZjE",
  },
]
